//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Empresa.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELETE
        ///  FROM OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_empresa.num_serie_lme
        ///        FROM  lor_man_empresa
        ///        WHERE lor_man_empresa.num_serie_lme = {1}
        ///    &apos;
        ///  ).
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT  tabela.existe
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  DISTINCT 1 AS existe
        ///        FROM  lor_man_empresa
        ///        WHERE lor_man_empresa.cod_empresa = &apos;{1}&apos;
        ///    &apos;
        ///  ) AS tabela.
        /// </summary>
        internal static string ExisteAk {
            get {
                return ResourceManager.GetString("ExisteAk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT  tabela.existe
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  DISTINCT 1 AS existe
        ///        FROM  lor_man_linha_montagem
        ///        WHERE lor_man_linha_montagem.num_serie_lme = {1}
        ///    &apos;
        ///  ) AS tabela.
        /// </summary>
        internal static string ExisteDependencias {
            get {
                return ResourceManager.GetString("ExisteDependencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT  tabela.existe
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  DISTINCT 1 AS existe
        ///        FROM  lor_man_empresa
        ///        WHERE lor_man_empresa.num_serie_lme = {1}
        ///    &apos;
        ///  ) AS tabela.
        /// </summary>
        internal static string ExistePk {
            get {
                return ResourceManager.GetString("ExistePk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT
        ///  INTO OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_empresa.cod_empresa
        ///           ,  lor_man_empresa.den_empresa
        ///           ,  lor_man_empresa.den_empresa_reduz
        ///        FROM  lor_man_empresa
        ///    &apos;
        ///  )
        ///  VALUES
        ///  (
        ///    UPPER ( &apos;{1}&apos; )
        ///  , UPPER ( &apos;{2}&apos; )
        ///  , UPPER ( &apos;{3}&apos; )
        ///  ).
        /// </summary>
        internal static string InsertRecord {
            get {
                return ResourceManager.GetString("InsertRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT  tabela.serie_empresa
        ///     ,  tabela.codigo_empresa
        ///     ,  tabela.descricao_empresa
        ///     ,  tabela.descricao_empresa_reduzida
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_empresa.num_serie_lme           AS serie_empresa
        ///           ,  TRIM(lor_man_empresa.cod_empresa)       AS codigo_empresa
        ///           ,  TRIM(lor_man_empresa.den_empresa)       AS descricao_empresa
        ///           ,  TRIM(lor_man_empresa.den_empresa_reduz) AS descricao_empresa_reduzida
        ///        FROM  lor_man_empres [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QueryRecordAk {
            get {
                return ResourceManager.GetString("QueryRecordAk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT  tabela.serie_empresa
        ///     ,  tabela.codigo_empresa
        ///     ,  tabela.descricao_empresa
        ///     ,  tabela.descricao_empresa_reduzida
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_empresa.num_serie_lme           AS serie_empresa
        ///           ,  TRIM(lor_man_empresa.cod_empresa)       AS codigo_empresa
        ///           ,  TRIM(lor_man_empresa.den_empresa)       AS descricao_empresa
        ///           ,  TRIM(lor_man_empresa.den_empresa_reduz) AS descricao_empresa_reduzida
        ///        FROM  lor_man_empres [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QueryRecordAll {
            get {
                return ResourceManager.GetString("QueryRecordAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT  tabela.serie_empresa
        ///     ,  tabela.codigo_empresa
        ///     ,  tabela.descricao_empresa
        ///     ,  tabela.descricao_empresa_reduzida
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_empresa.num_serie_lme           AS serie_empresa
        ///           ,  TRIM(lor_man_empresa.cod_empresa)       AS codigo_empresa
        ///           ,  TRIM(lor_man_empresa.den_empresa)       AS descricao_empresa
        ///           ,  TRIM(lor_man_empresa.den_empresa_reduz) AS descricao_empresa_reduzida
        ///        FROM  lor_man_empres [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QueryRecordPk {
            get {
                return ResourceManager.GetString("QueryRecordPk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Empresa.
        /// </summary>
        internal static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a lor_man_empresa.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_empresa.den_empresa       AS descricao_empresa
        ///           ,  lor_man_empresa.den_empresa_reduz AS descricao_empresa_reduzida
        ///        FROM  lor_man_empresa
        ///        WHERE lor_man_empresa.num_serie_lme = {1}
        ///    &apos;
        ///  ) 
        ///  SET  descricao_empresa          = &apos;{2}&apos;
        ///    ,  descricao_empresa_reduzida = &apos;{3}&apos;.
        /// </summary>
        internal static string UpdateRecord {
            get {
                return ResourceManager.GetString("UpdateRecord", resourceCulture);
            }
        }
    }
}
